spring.application.name=osinspector

spring.datasource.url=jdbc:firebirdsql://localhost:3050/C:/dados/banco.fdb?charSet=utf-8
spring.datasource.username=SYSDBA
spring.datasource.password=masterkey
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

# Dialeto para o Hibernate reconhecer as funções do Firebird
spring.jpa.database-platform=org.hibernate.dialect.FirebirdDialect


